USE [master]
GO

/****** Object:  Database [DB_AvaliacaoFinalDS]    Script Date: 23/11/2021 23:56:47 ******/
CREATE DATABASE [DB_AvaliacaoFinalDS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DB_AvaliacaoFinalDS', FILENAME = N'E:\Program Files (x86)\SQL\MSSQL15.MSSQLSERVER\MSSQL\DATA\DB_AvaliacaoFinalDS.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DB_AvaliacaoFinalDS_log', FILENAME = N'E:\Program Files (x86)\SQL\MSSQL15.MSSQLSERVER\MSSQL\DATA\DB_AvaliacaoFinalDS_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DB_AvaliacaoFinalDS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DB_AvaliacaoFinalDS] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DB_AvaliacaoFinalDS] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DB_AvaliacaoFinalDS] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DB_AvaliacaoFinalDS] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DB_AvaliacaoFinalDS] SET ARITHABORT OFF 
GO

ALTER DATABASE [DB_AvaliacaoFinalDS] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DB_AvaliacaoFinalDS] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DB_AvaliacaoFinalDS] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DB_AvaliacaoFinalDS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DB_AvaliacaoFinalDS] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DB_AvaliacaoFinalDS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DB_AvaliacaoFinalDS] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DB_AvaliacaoFinalDS] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DB_AvaliacaoFinalDS] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DB_AvaliacaoFinalDS] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DB_AvaliacaoFinalDS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DB_AvaliacaoFinalDS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DB_AvaliacaoFinalDS] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DB_AvaliacaoFinalDS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DB_AvaliacaoFinalDS] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DB_AvaliacaoFinalDS] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DB_AvaliacaoFinalDS] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DB_AvaliacaoFinalDS] SET RECOVERY FULL 
GO

ALTER DATABASE [DB_AvaliacaoFinalDS] SET  MULTI_USER 
GO

ALTER DATABASE [DB_AvaliacaoFinalDS] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DB_AvaliacaoFinalDS] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DB_AvaliacaoFinalDS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DB_AvaliacaoFinalDS] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DB_AvaliacaoFinalDS] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DB_AvaliacaoFinalDS] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [DB_AvaliacaoFinalDS] SET QUERY_STORE = OFF
GO

ALTER DATABASE [DB_AvaliacaoFinalDS] SET  READ_WRITE 
GO

USE [DB_AvaliacaoFinalDS]
GO

/****** Object:  Table [dbo].[Users]    Script Date: 23/11/2021 23:57:45 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Users](
	[userId] [int] IDENTITY(1,1) NOT NULL,
	[username] [varchar](200) NOT NULL,
	[password] [varchar](200) NOT NULL,
	[role] [varchar](50) NOT NULL,
 CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED 
(
	[userId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[Produto]    Script Date: 23/11/2021 23:57:27 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Produto](
	[idProduto] [int] IDENTITY(1,1) NOT NULL,
	[nomeProduto] [varchar](200) NOT NULL,
	[categoria] [varchar](200) NULL,
	[quantidadeEstoque] [int] NULL,
	[precoVenda] [numeric](18, 2) NULL,
 CONSTRAINT [PK_Produto] PRIMARY KEY CLUSTERED 
(
	[idProduto] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO